### ISSUE TITLE
z_shieldcoinbase returned error: Error: z_shieldcoinbase is disabled. code -4 

### ISSUE THREAD

**Issue by Gadflyii** [coinfoundry/miningcore#223]
What did I do wrong? Where is this enabled for a z-based coin? The config has the Z-addy and the t-addy for the pool, but when the payment process goes to shield the balance, I get these errors:

[2018-02-26 15:53:35.5489] [I] [Vision] [ZCash Payout Handler] Shielding ZCash Coinbase funds 
[2018-02-26 15:53:35.5489] [E] [Vision] [ZCash Payout Handler] z_shieldcoinbase returned error: Error: z_shieldcoinbase is disabled. code -4

**Comment by oliverw** [comment]
In earlier versions of ZCash "z_shieldcoinbase" had to be enabled via command-line switch. Run zcashd (or whatever its called for your coin) and look for "experimental".

**Comment by oliverw** [comment]
Depends on the interval set in your payment processing config.

**Comment by lucas556** [comment]
@oliverw Using release 19, the following error occurred:

`[PayoutManager] [zec1] Payment processing failed Newtonsoft.Json.JsonReaderException: Error reading string. Unexpected token: StartObject. Path ''.`

zcash.conf

`addnode=testnet.z.cash
rpcuser=test
rpcpassword=test
showmetrics=0
gen=0
testnet=1
rpcallowip=172.16.0.5
rpcport=8333
zshieldcoinbase=1
experimentalfeatures=1`

**Comment by Gadflyii** [comment]
Same error here

**Comment by calvintam236** [comment]
@Gadflyii is this issue solved in release 20?

**Comment by lucas556** [comment]
@calvintam236 Still not solved, the same mistake, but the miners can receive the fee.

**Comment by oliverw** [comment]
Fixed in master.
