### ISSUE TITLE
Wrong transaction url for dash

### ISSUE THREAD

**Issue by shtse8** [coinfoundry/miningcore#23]
https://github.com/coinfoundry/miningcore/blob/80f6ebe7590a7137a33f3ea04bf6e6f89e6ff500/src/MiningCore/Api/ApiServer.cs#L105
DASH is not the same as DSH.
DASH is Dash
DSH is Dashcoin

The current url is https://chainradar.com/dsh/transaction/[txnid]

The correct url should be 
https://chainz.cryptoid.info/dash/tx.dws?[txnid].htm

**Comment by oliverw** [comment]
Already fixed by #b922261aeda922e47ddb221aa85c702ae8d3390a

**Comment by shtse8** [comment]
The blocks endpoint infoLink is still wrong. 
the url should be placed with block height instead of tnx hash.

**Comment by oliverw** [comment]
Urls using the hash seem to work fine: https://chainz.cryptoid.info/dash/block.dws?00000000000001bd7c1aabaacd7a176b3f347723ce449110c6912da6962fdfeb.htm

**Comment by shtse8** [comment]
```json
{
blockheight: 742811,
status: 3,
transactionConfirmationData: "c9912c782bece63abf234d7d75d532e6415ecee516f816fb1c3c755b34cdd4e9",
reward: 1.79557754,
infoLink: "https://chainz.cryptoid.info/dash/block.dws?c9912c782bece63abf234d7d75d532e6415ecee516f816fb1c3c755b34cdd4e9.htm",
created: "2017-09-24T22:46:38.099633"
}
```

But All my links are broken.

**Comment by oliverw** [comment]
I stand corrected. Working on it.

**Comment by oliverw** [comment]
Please verify and close if fixed by 986ef87082ed4d34100be10ba6de161176f5568e

**Comment by shtse8** [comment]
It works now. Thanks.
