### ISSUE TITLE
ETC - Bug Block Revard and Payments PPLNS

### ISSUE THREAD

**Issue by OleksandrBlack** [coinfoundry/miningcore#289]
### Description
ETC POOL - etc.lucky-mining.com.ua
Wrong amount of coins revard.
Invalid allocation of PPLNS.

### Steps to Reproduce
![pool_revard](https://user-images.githubusercontent.com/13917465/37977930-8011bc6c-31ed-11e8-9cb3-c164382ad08e.png)
![gast](https://user-images.githubusercontent.com/13917465/37977948-8b11cb02-31ed-11e8-9b36-3d8499c22c55.png)
![payments](https://user-images.githubusercontent.com/13917465/37977958-8f42c67c-31ed-11e8-92c1-d95aed12947e.png)
![gast2](https://user-images.githubusercontent.com/13917465/37977964-9255e0a6-31ed-11e8-8c83-5fdb17d96c10.png)

### Version
Release 21

### Parity.log
```
2018-03-27 04:44:35    18/25 peers   13 MiB chain 68 MiB db 0 bytes queue 22 KiB sync  RPC:  0 conn,  5 req/s, 3455 µs
2018-03-27 04:44:59  Imported #5618960 5b98…9000 (0 txs, 0.00 Mgas, 18.15 ms, 0.53 KiB)
2018-03-27 04:44:59  Submitted block imported OK. #5618960: 5b98d9b52afd1ff5748d7ef67bd96a4dbc2a779e8562b74a2a68061347aa9000
2018-03-27 04:45:10    18/25 peers   13 MiB chain 66 MiB db 0 bytes queue 22 KiB sync  RPC:  0 conn,  9 req/s, 3334 µs
2018-03-27 04:45:11  Imported #5618961 20a8…0334 (3 txs, 0.06 Mgas, 2.79 ms, 0.87 KiB)
2018-03-27 04:45:14  Imported #5618962 f784…0c9f (7 txs, 0.22 Mgas, 6.60 ms, 1.62 KiB)
```

```
2018-03-27 11:58:14  Imported #5620481 7612…3e2c (7 txs, 0.15 Mgas, 2.67 ms, 1.30 KiB)
2018-03-27 11:58:23    18/25 peers   37 MiB chain 68 MiB db 0 bytes queue 22 KiB sync  RPC:  0 conn,  8 req/s, 7990 µs
2018-03-27 11:58:31  Error importing transaction: Transaction(InsufficientBalance { balance: 6170737534989629494, cost: 6179537534989629000 })
2018-03-27 11:58:33  Imported #5620482 07a4…a5cd (7 txs, 0.18 Mgas, 3.86 ms, 1.43 KiB)
2018-03-27 11:58:36  Error importing transaction: Transaction(InsufficientBalance { balance: 6170737534989629494, cost: 6179537534989629000 })
2018-03-27 11:58:41  Error importing transaction: Transaction(InsufficientBalance { balance: 6170737534989629494, cost: 6179537534989629000 })
2018-03-27 11:58:42  Imported #5620483 91a1…1af8 (9 txs, 0.19 Mgas, 7.20 ms, 1.54 KiB)
2018-03-27 11:58:43  Imported #5620483 cb1a…856c (9 txs, 0.19 Mgas, 5.58 ms, 1.53 KiB)
2018-03-27 11:58:46  Error importing transaction: Transaction(InsufficientBalance { balance: 6170737534989629494, cost: 6179537534989629000 })
2018-03-27 11:58:51  Error importing transaction: Transaction(InsufficientBalance { balance: 6170737534989629494, cost: 6179537534989629000 })
2018-03-27 11:58:56  Error importing transaction: Transaction(InsufficientBalance { balance: 6170737534989629494, cost: 6179537534989629000 })
2018-03-27 11:58:58    18/25 peers   37 MiB chain 68 MiB db 0 bytes queue 22 KiB sync  RPC:  0 conn, 10 req/s, 455 µs
2018-03-27 11:59:31  Imported #5620484 b4b1…3c5e (0 txs, 0.00 Mgas, 1.02 ms, 0.52 KiB)
2018-03-27 11:59:33    18/25 peers   37 MiB chain 68 MiB db 0 bytes queue 22 KiB sync  RPC:  0 conn,  4 req/s, 357 µs
```

### miningcore.log

```
[2018-03-27 15:29:07.0829] [I] [etc1] [Ethereum Job Manager] Submitting block 5621244 
[2018-03-27 15:29:07.1091] [I] [etc1] [Ethereum Job Manager] Daemon accepted block 5621244 submitted by 0xfbef7a4f2f5c1a1af5203b8802ba79519e18b02f 
[2018-03-27 15:29:07.1091] [I] [etc1] [Pool] [0HLCJCFM1URTG] Share accepted: D=1,164 
```

```
[2018-03-27 15:42:50.9907] [I] [PayoutManager] Processing payments for pool etc1 
[2018-03-27 15:42:51.0104] [I] [etc1] [Ethereum Payout Handler] Unlocked block 5621244 worth 5 ETC 
[2018-03-27 15:42:51.0104] [I] [PayoutManager] Processing payments for pool etc1, block 5621244 
[2018-03-27 15:42:51.0104] [I] [PPLNS] Fetching page 0 of shares for pool etc1, block 5621244 
[2018-03-27 15:42:51.5822] [I] [PPLNS] Fetching page 1 of shares for pool etc1, block 5621244 
[2018-03-27 15:42:51.9040] [I] [etc1] [Pool] [0HLCJCFM1URT3] Share accepted: D=1,164 
[2018-03-27 15:42:52.0826] [I] [etc1] [Pool] [0HLCJCFM1URTJ] Share accepted: D=1,164 
[2018-03-27 15:42:52.1627] [I] [PPLNS] Balance-calculation for pool etc1, block 5621244 completed with accumulated score 2 (100%) 
[2018-03-27 15:42:52.1627] [I] [PPLNS] Adding 4,2915 ETC to balance of 0xfbef7a4f2f5c1a1af5203b8802ba79519e18b02f for 285,52 T (285523408492017) shares for block 5621244 
[2018-03-27 15:42:52.1685] [I] [PPLNS] Adding 0,31119 ETC to balance of 0x1421bd523ebfae0599b93b6c88cc0a0184fad3a1 for 20,71 T (20710581713990,1) shares for block 5621244 
[2018-03-27 15:42:52.1705] [I] [PPLNS] Adding 0,20424 ETC to balance of 0x641d550a1dc24c8afea5fc080475d215d27e14a1 for 13,6 T (13596448345501) shares for block 5621244 
[2018-03-27 15:42:52.1705] [I] [PPLNS] Adding 0,05815 ETC to balance of 0x4213d1c709684fbdbcf8b27de421744e6cdeb9d4 for 3,87 T (3870842297471,11) shares for block 5621244 
[2018-03-27 15:42:52.1754] [I] [PPLNS] Adding 0,11441 ETC to balance of 0xA93A0e79894A9C9D242E7EC3a0a1bAB8d34078ea for 7,61 T (7614183731528,17) shares for block 5621244 
[2018-03-27 15:42:52.1773] [I] [PPLNS] Adding 0,01801 ETC to balance of 0xb0dB1E9827ECdb9D3EE0A330B20A5888204ce865 for 1,2 T (1199864375838,08) shares for block 5621244 
[2018-03-27 15:42:52.2071] [I] [PPLNS] Fetching page 0 of discarded shares for pool etc1, block 5621244 
[2018-03-27 15:42:52.7012] [I] [PPLNS] Fetching page 1 of discarded shares for pool etc1, block 5621244 
[2018-03-27 15:42:53.0964] [I] [PPLNS] 228,92 T (228916595709895) total discarded shares, block 5621244 
[2018-03-27 15:42:53.0978] [I] [PPLNS] 0xfbef7a4f2f5c1a1af5203b8802ba79519e18b02f = 208,24 T (208235882746120) discarded shares, block 5621244 
[2018-03-27 15:42:53.0978] [I] [PPLNS] 0x1421bd523ebfae0599b93b6c88cc0a0184fad3a1 = 9,15 T (9153477842631,26) discarded shares, block 5621244 
[2018-03-27 15:42:53.0978] [I] [PPLNS] 0x641d550a1dc24c8afea5fc080475d215d27e14a1 = 4,55 T (4546350392204,94) discarded shares, block 5621244 
[2018-03-27 15:42:53.0978] [I] [PPLNS] 0xA93A0e79894A9C9D242E7EC3a0a1bAB8d34078ea = 3,94 T (3937242804361,87) discarded shares, block 5621244 
[2018-03-27 15:42:53.0978] [I] [PPLNS] 0x4213d1c709684fbdbcf8b27de421744e6cdeb9d4 = 2,32 T (2323346481108,67) discarded shares, block 5621244 
[2018-03-27 15:42:53.0978] [I] [PPLNS] 0xb0dB1E9827ECdb9D3EE0A330B20A5888204ce865 = 720,3 G (720295443467,784) discarded shares, block 5621244 
[2018-03-27 15:42:53.0978] [I] [PPLNS] Deleting 93657 discarded shares before 2018-03-26T20:20:02.4625380 
[2018-03-27 15:42:53.2643] [I] [PPLNS] 332,52 T (332515328956345,46) shares contributed to a total payout of 4,9975 ETC (100,00% of block reward) to 6 addresses 
[2018-03-27 15:42:53.2832] [I] [etc1] [Ethereum Payout Handler] Sending 4,2915 ETC to 0xfbef7a4f2f5c1a1af5203b8802ba79519e18b02f 
[2018-03-27 15:42:53.3297] [I] [etc1] [Ethereum Payout Handler] Payout transaction id: 0x68477f30141f7dc8a1d89d9bda89e22874159258344e4b8bfb6d04263c1b0461 
[2018-03-27 15:42:53.3382] [I] [etc1] [Ethereum Payout Handler] Sending 0,31119 ETC to 0x1421bd523ebfae0599b93b6c88cc0a0184fad3a1 
[2018-03-27 15:42:53.3437] [I] [etc1] [Ethereum Job Manager] New block 5621289 detected 
[2018-03-27 15:42:53.3437] [I] [etc1] [Pool] Broadcasting job 
[2018-03-27 15:42:53.3759] [I] [etc1] [Ethereum Payout Handler] Payout transaction id: 0xb6ba63d162275e6b82990671d94e5f3872ddfff7b66e70f27a530a1d8344e07d 
[2018-03-27 15:42:53.3824] [I] [etc1] [Ethereum Payout Handler] Sending 0,20424 ETC to 0x641d550a1dc24c8afea5fc080475d215d27e14a1 
[2018-03-27 15:42:53.4223] [I] [etc1] [Ethereum Payout Handler] Payout transaction id: 0x2508beba1f733c4005253d14d0dd15d090597673cc2613c1be947dd0a15e4979 
[2018-03-27 15:42:53.4279] [I] [etc1] [Ethereum Payout Handler] Sending 0,11097 ETC to 0x4213d1c709684fbdbcf8b27de421744e6cdeb9d4 
[2018-03-27 15:42:53.4786] [I] [etc1] [Ethereum Payout Handler] Payout transaction id: 0x75c3f1788ea95ecd106f8ae2cfe215b0937cb6f659088a2af6e3e2e9a93329ed 
[2018-03-27 15:42:53.4902] [I] [etc1] [Ethereum Payout Handler] Sending 0,20896 ETC to 0xA93A0e79894A9C9D242E7EC3a0a1bAB8d34078ea 
[2018-03-27 15:42:53.5393] [I] [etc1] [Ethereum Payout Handler] Payout transaction id: 0x4ce1fc509c47fa27c84a7f171547cba2afedcadb4deced28b6955f1d16420bd5 
```

### Parity config
```
[parity]

chain = "classic"
mode = "active"
auto_update = "all"
release_track = "stable"
base_path = "/MYDIR"
db_path = "/MYDIR/chains"
keys_path = "/MYDIR/keys"
identity = ""
light = false

[ui]
disable = true

[dapps]
disable = true

[ipc]
disable = true

[network]
discovery = false

[rpc]
interface = "0.0.0.0"
cors = ["32"]
apis = ["eth,net,web3,personal,parity,parity_pubsub,rpc"]
port = 8645

[websockets]
interface = "all"
port = 8646

[mining]
author = "0xa773717247a7ab6a1281665954f440042281cd9f"

[misc]
log_file = "/MYDIR/parity.log"
logging = "info"
color = true

[footprint]
db_compaction = "ssd"
cache_size = 512

[account]
unlock = ["0xa773717247a7ab6a1281665954f440042281cd9f"]
password = ["/MYDIR/password.file"]
keys_iterations = 10240
```

### miningcore config
```
{
    "logging": {
        "level": "info",
        "enableConsoleLog": true,
        "enableConsoleColors": true,
        "logFile": "/MYDIR/logs/etc.log",
        "logBaseDirectory": "/MYDIR/logs/",
        "perPoolLogFile": false
    },
	"dagDir": "/MYDIR/dag_etc",
    "banning": {
        "manager": "integrated",
        "banOnJunkReceive": true,
        "banOnInvalidShares": false
    },
	"api":{
    "enabled":true,
    "listenAddress":"**MYIP**",
    "port":4000
	},
    "notifications": {
        "enabled": false,
        "email": {
            "host": "smtp.example.com",
            "port": 587,
            "user": "user",
            "password": "password",
            "fromAddress": "info@yourpool.org",
            "fromName": "support"
        },
        "admin": {
            "enabled": false,
            "emailAddress": "user@example.com",
            "notifyBlockFound": true
        }
    },
    "persistence": {
        "postgres": {
            "host": "127.0.0.1",
            "port": 5433,
            "user": "miningcore",
            "password": "**MYPASS**",
            "database": "miningcore"
        }
    },
	"devDonation":0.0,
    "paymentProcessing": {
        "enabled": true,
        "interval": 600,
        "shareRecoveryFile": "recovered-shares.txt"
    },
    "pools": [{
        "id": "etc1",
        "enabled": true,
        "coin": {
            "type": "ETC"
        },
        "address": "0xa773717247a7ab6a1281665954f440042281cd9f",
        "rewardRecipients": [{
                "type": "op",
                "address": "0xa773717247a7ab6a1281665954f440042281cd9f",
                "percentage": 0
        }],
        "blockRefreshInterval": 100,
        "clientConnectionTimeout": 600,
        "banning": {
            "enabled": true,
            "time": 600,
            "invalidPercent": 50,
            "checkThreshold": 50
        },
        "ports": {
            "3072": {
			"listenAddress": "109.237.93.186",
                "difficulty": 2.328830926874709,
                "varDiff": {
                    "minDiff": 1.164415463437354,
                    "maxDiff": 2.328830926874709,
                    "targetTime": 15,
                    "retargetTime": 90,
                    "variancePercent": 30
                }
            },
            "3073": {
			"listenAddress": "109.237.93.186",
                "difficulty": 0.1,
                "varDiff": {
                    "minDiff": 0.5,
                    "maxDiff": 1.5,
                    "targetTime": 15,
                    "retargetTime": 90,
                    "variancePercent": 30
                }
            }
        },
        "daemons": [
            {
                "host": "127.0.0.1",
                "port": 8645,
                "user": "user",
                "password": "password"
            }
        ],
        "paymentProcessing": {
            "enabled": true,
            "minimumPayment": 0.1,
            "payoutScheme": "PPLNS",
            "payoutSchemeConfig": {
                "factor": 2.0
            },
            "coinbasePassword": "**MYBASEPASS**",
            "keepUncles": false,
            "keepTransactionFees": false
        }
    }]
}
```
I understand that there are 4 coins in the ETC block. And it is 4 that should divide PPLNS.
I ask help @oliverw pls.

**Comment by oliverw** [comment]
@OleksandrBlack That explains why coinfoundry's ETC pool recently ran out of funds. Fix incoming.

**Comment by OleksandrBlack** [comment]
@oliverw I ask you. Give direction in the direction of the problem and correct it. Can on the code part where 5 coins are indicated. I want to fix this as quickly as possible. Thanks in advance.!)

**Comment by oliverw** [comment]
Fixed in c6df5b5f0c8f9b9b8b360540f25a34529ce2a097

**Comment by OleksandrBlack** [comment]
@oliverw @calvintam236 
http://ethc.lucky-mining.com.ua/blocks.html
Block № 5626570 - Revard 4.13531

https://gastracker.io/block/5626570
Miner Reward 4.0103 Ether

**The problem is not solved**

**Comment by oliverw** [comment]
@OleksandrBlack Gastracker shows the raw block reward without tx fees.
